sudo: false
cache:
  directories:
  - "$HOME/.gradle"
jdk:
- oraclejdk8
before_script:
script: "./travis-build.sh"
env:
  global:
  - secure: dAqxhUr8hdZDY4+r48/J14GWmtM0ataRz6wF/LCcxRPXpZM8+52WYvfNa/L0HXfTd7aGgL+IHxKJ/DdAABWwFQhGkrihyLENQbzXP4zvSuUucIqMvK8v3bLorwXzd9Yy3VixccsmeYL5j0HzVObopdGcl4o0KYiBq6ZSDlFkPQubiaH33cNUL7wnffP5veHOHLljITFl7JiWxdELvldeAlbn+UgRGmrym+Niw5w8TGmsxB8REUVQ9Rke26jWUL+sGBx42I2bYPNJs6uAv5UP5R7bShEBoONQgP7R0tP26G7PMQvK0E8jDVNODb/hf2IK4+QAx2NSl8UZ4g3UTS4l/xfvY8PMNOYo+x2zbqGMGo0CIERMOp6X/JkqAgjZQKYI368gUe+WMBLmrgcc+Sabj4JDSWGcbp+82NJJYpxFHGyMUT5d7lxs7X7peDqA+vlRMjAW9CzF/DZO83GUDbMvlDjFEi4PBRTCd75Fxg1LPhw6ufIKuaib5L12MTQwhS4GmhUup+PevxPSKROkyGUyGkhFIguK61iza3weXK7jfSj8WchxTNzLBZa5noXavqYcJY1OqUgtHC5X3cObfmDWUZuTmyTXIDsHHCgu4HS/sE9MrEBfnu0l8kfeL+SnGID2CVGan244fKwGZO+D0VCMpQz+YHH0dzSIysMbcpDXCbk=
  - secure: Xnm4Bg6jq5UdsSmHuZagCH8uPEJtIU6mpHkhVO1NwJTvOs26xN4JfVqwKCUwaw4B8F/QPANixkh6NU6AJ6voL0cV6pU4dFQT9Fimz5q85Rs7tpldS8trcNKw6iDuN+XibCvRlwERlJW5iR1ixx9uUTEwYYBA7/Zvqmz51USabQmO9lDaNtsYJ7i9q//CdQY1bUTuWIEBOQFa/QCJAIGwjTyYXO9MoZhOcBlO7vjodS3iD48/nHwzP1gZA6WpdJd4ixw+VAAmjpR0vQec98qVb5zEj8c6hPWCGKfW21vu68B4YxZl4ifr7dUSMeY4aK6HRo+ogzwoMICuHnl0wxo8DzzZDvUvR9+4LN7lDKEkTEg1ZuzXwYGWkLcUtb+eNio9UnoScen1eJiNR7e2c3OiifeHgNME9kbi8ZC/n+QdEOiGVF/s3vSxcCbC4pUKopT3fttoq/KhNadQChtTce2x5ax+of8AM/yWnlOUp0hKFPHaEQHfxCSFvGD7qxptgpM8Kh2qxVte5m9DWcZ7aJ1C+ziKjBa3NvDu1LOdz1s/fuui9/7BlcXHMCaDoGomdLMkMue5QnyfLZYT0VQw6EQqYqhPFKw3nEBgIr4Nk0+FEAIoCFAY9djAm97QXDMwLObc5JiLlZXZ0F41lJMe5t2bg11uWMes6PnRCaKdxd9ncu0=
